language: "nl"
reviews:
  auto_review:
    enabled: true
    base_branches:
      - ".*"
  review_status: true
  path_filters: []
  tools:
    shellcheck:
      enabled: true
  profile: "assertive"
chat:
  auto_reply: true
