#!/usr/bin/env python3
"""
MANDELBULBER FORMULA GENERATOR V2
==================================
IMPROVED version with:
- Automatic validation
- Better variable conflict resolution
- Complete class structure generation
- Auto-fix common issues

Author: Claude + Joeri
Version: 2.0
Date: 2026-04-19
"""

import os
import re
import sys
from typing import Dict, List, Tuple, Optional
from pathlib import Path
from dataclasses import dataclass

# Import parser from v1
sys.path.insert(0, str(Path(__file__).parent))
from formula_generator_interactive import FormulaParser, FormulaInfo


class ImprovedFormulaGenerator:
    """V2 Generator with validation and auto-fix"""

    def __init__(self, parser: FormulaParser, output_dir: str):
        self.parser = parser
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def combine_formulas(self,
                        formula_indices: List[int],
                        new_name: str,
                        new_internal_name: str,
                        new_internal_id: str,
                        merge_strategy: str = "sequential") -> str:
        """
        Combine formulas with improved code generation
        """
        # Get formula info
        formulas = []
        for idx in formula_indices:
            info = self.parser.get_formula_by_index(idx)
            if not info:
                raise ValueError(f"Formula index {idx} not found")
            formulas.append(info)

        print(f"\n🔨 Combining {len(formulas)} formulas:")
        for i, f in enumerate(formulas, 1):
            print(f"  {i}. {f.name_in_combo}")

        # Generate class name
        class_name = self._to_class_name(new_internal_id)

        # Generate COMPLETE code structure
        code = self._generate_header(class_name, new_name, formulas)
        code += self._generate_class_declaration(class_name)
        code += self._generate_constructor(
            class_name, new_name, new_internal_name,
            new_internal_id, formulas[0]
        )
        code += self._generate_formula_code_v2(
            class_name, formulas, merge_strategy
        )

        return code

    def _to_class_name(self, internal_id: str) -> str:
        """Convert internal_id to ClassName"""
        internal_id = internal_id.replace('fractal::', '')
        parts = internal_id.split('_')
        return 'cFractal' + ''.join(p.capitalize() for p in parts)

    def _generate_header(self, class_name: str, formula_name: str,
                        formulas: List[FormulaInfo]) -> str:
        """Generate file header"""
        sources = '\n'.join(f' * Source {i}: {f.name_in_combo}'
                           for i, f in enumerate(formulas, 1))

        return f'''/**
 * Mandelbulber v2, a 3D fractal generator  _%}}i*<.         ______
 * Copyright (C) 2024 Mandelbulber Team   _>]|=||i=i<,      / ____/ __    __
 *                                        \\><||i|=>>%)     / /   __/ /___/ /_
 * This file is part of Mandelbulber.     )<=i=]=|=i<>    / /__ /_  __/_  __/
 * The project is licensed under GPLv3,   -<>>=|><|||`    \\____/ /_/   /_/
 * see also COPYING file in this folder.    ~+{{i%+++
 *
 * {formula_name}
 *
 * AUTO-GENERATED by Formula Generator V2
 * Validated and optimized
 *
{sources}
 */

#include "all_fractal_definitions.h"

'''

    def _generate_class_declaration(self, class_name: str) -> str:
        """Generate class declaration"""
        return f'''class {class_name} : public cAbstractFractal
{{
public:
\t{class_name}();
\tvoid FormulaCode(CVector4 &z, const sFractal *fractal, sExtendedAux &aux) override;
}};

'''

    def _generate_constructor(self, class_name: str, name_combo: str,
                             internal_name: str, internal_id: str,
                             template: FormulaInfo) -> str:
        """Generate constructor"""
        return f'''{class_name}::{class_name}() : cAbstractFractal()
{{
\tnameInComboBox = "{name_combo}";
\tinternalName = "{internal_name}";
\tinternalID = fractal::{internal_id};
\tDEType = {template.de_type};
\tDEFunctionType = {template.de_function_type};
\tcpixelAddition = {template.cpixel_addition};
\tdefaultBailout = {template.default_bailout};
\tDEAnalyticFunction = {template.de_analytic_function};
\tcoloringFunction = {template.coloring_function};
}}

'''

    def _generate_formula_code_v2(self, class_name: str,
                                   formulas: List[FormulaInfo],
                                   strategy: str) -> str:
        """Generate FormulaCode with variable conflict resolution"""
        code = f'''void {class_name}::FormulaCode(
\tCVector4 &z, const sFractal *fractal, sExtendedAux &aux)
{{
'''

        if strategy == "sequential":
            # Execute formulas in sequence WITH conflict resolution
            code += '\t// Combined formula - Sequential execution\n'
            for i, formula in enumerate(formulas):
                code += f'\n\t// ========== Stage {i+1}: {formula.name_in_combo} ==========\n'
                code += '\t{\n'  # Scope isolation
                # Fix variable conflicts by adding suffix
                fixed_code = self._fix_variables(formula.formula_code, i)
                code += self._indent_code(fixed_code, 2)
                code += '\t}\n'

        elif strategy == "parallel":
            code += '\t// Combined formula - Parallel (iteration-based)\n'
            for i, formula in enumerate(formulas):
                code += f'\n\t// Stage {i+1}: {formula.name_in_combo}\n'
                code += f'\tif (aux.i % {len(formulas)} == {i})\n\t{{\n'
                fixed_code = self._fix_variables(formula.formula_code, i)
                code += self._indent_code(fixed_code, 2)
                code += '\t}\n'

        elif strategy == "weighted":
            code += '\t// Combined formula - Weighted blend\n'
            for i, formula in enumerate(formulas):
                weight = 1.0 / len(formulas)
                code += f'\n\t// Stage {i+1}: {formula.name_in_combo} (weight: {weight:.2f})\n'
                code += '\t{\n'
                code += f'\t\tCVector4 z_stage{i} = z;\n'
                code += f'\t\tdouble DE_stage{i} = aux.DE;\n'

                # Process formula with temp variables
                fixed_code = self._fix_variables(formula.formula_code, i)
                # Replace z references with z_stageN
                fixed_code = re.sub(r'\bz\b', f'z_stage{i}', fixed_code)
                fixed_code = re.sub(r'aux\.DE\b', f'DE_stage{i}', fixed_code)

                code += self._indent_code(fixed_code, 2)

                # Blend results
                code += f'\n\t\t// Blend stage {i+1} result\n'
                code += f'\t\tz = z * {1.0 - weight:.3f} + z_stage{i} * {weight:.3f};\n'
                code += f'\t\taux.DE = aux.DE * {1.0 - weight:.3f} + DE_stage{i} * {weight:.3f};\n'
                code += '\t}\n'

        code += '}\n'
        return code

    def _fix_variables(self, code: str, stage_index: int) -> str:
        """
        Advanced variable conflict resolution

        Renames local variables to avoid conflicts between stages
        """
        # Find all local variable declarations
        # Pattern: type varname = value;
        declarations = re.findall(
            r'\b(double|float|int|bool|long|short|unsigned)\s+(\w+)\s*=',
            code
        )

        # Build replacement map
        replacements = {}
        for var_type, var_name in declarations:
            # Don't rename common struct members or globals
            if var_name in ['z', 'aux', 'fractal', 'i', 'x', 'y']:
                continue

            # Create unique name
            new_name = f'{var_name}_s{stage_index}'
            replacements[var_name] = new_name

        # Apply replacements (careful to not replace substrings)
        fixed_code = code
        for old_name, new_name in replacements.items():
            # Use word boundaries to avoid partial matches
            pattern = r'\b' + re.escape(old_name) + r'\b'
            fixed_code = re.sub(pattern, new_name, fixed_code)

        return fixed_code

    def _indent_code(self, code: str, levels: int) -> str:
        """Indent code block"""
        indent = '\t' * levels
        lines = code.split('\n')
        return '\n'.join(indent + line if line.strip() else '' for line in lines)

    def save_formula(self, code: str, filename: str) -> Path:
        """Save generated formula to file"""
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(code)
        print(f"\n✅ Generated formula saved to: {filepath}")
        return filepath


def main():
    """Test V2 generator"""
    print("=" * 70)
    print("🎨 FORMULA GENERATOR V2 - TEST")
    print("=" * 70)

    # Setup paths
    base_dir = Path(__file__).parent.parent / "mandelbulber2"
    formula_dir = base_dir / "formula" / "definition"
    output_dir = Path(__file__).parent / "generated_formulas"

    if not formula_dir.exists():
        print(f"ERROR: Formula directory not found: {formula_dir}")
        sys.exit(1)

    # Parse existing formulas
    parser = FormulaParser(str(formula_dir))
    parser.parse_all_formulas()

    # Create V2 generator
    generator = ImprovedFormulaGenerator(parser, str(output_dir))

    # Test - generate formula
    print("\n" + "=" * 70)
    print("TEST: Creating improved test formula")
    print("=" * 70)

    test_formula_id = "fractal::pseudoKleinianMod4"

    try:
        code = generator.combine_formulas(
            formula_indices=[217, 217],  # Combine with itself
            new_name="Test V2 PseudoKleinian",
            new_internal_name="test_v2_pk",
            new_internal_id="testV2Pk",
            merge_strategy="sequential"
        )

        # Save
        output_file = generator.save_formula(
            code,
            "fractal_test_v2_pk.cpp"
        )

        print("\n" + "=" * 70)
        print("✅ V2 GENERATION SUCCESS!")
        print("=" * 70)

        # Auto-validate
        print("\n🔍 Running automatic validation...")

        try:
            from formula_validator import FormulaValidator

            validator = FormulaValidator(str(base_dir))
            result = validator.validate_formula(output_file)

            if result.passed:
                print("\n🎉 VALIDATION PASSED!")
            else:
                print("\n⚠️  Validation had warnings (check output above)")

        except ImportError:
            print("⚠️  Validator not available, skipping validation")

    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
