/**
 * T>Wizard Demo formula
 * Generated by generate_complete_formula.py
 */

#include "fractal_transf_wizard_demo.h"

cFractalTransfWizardDemo::cFractalTransfWizardDemo() : cAbstractFractal()
{
	nameInComboBox = "T>Wizard Demo";
	internalName = "transf_wizard_demo";
	internalID = fractal::transfWizardDemo;
	DEType = analyticDEType;
	DEFunctionType = linearDEFunction;
	cpixelAddition = cpixelEnabledByDefault;
	defaultBailout = 100.0;
	DEAnalyticFunction = analyticFunctionLinear;
	coloringFunction = coloringFunctionDefault;
}

void cFractalTransfWizardDemo::FormulaCode(CVector4 &z, const sFractal *fractal, sExtendedAux &aux)
{
	// TODO: Implement your formula here
	// Available parameters:
	//   fractal->transformCommon.scale (double)

z *= fractal->transformCommon.scale;
}
