/**
 * T>Wizard Demo formula
 * Generated by generate_complete_formula.py
 */

#ifndef MANDELBULBER2_FORMULA_DEFINITION_FRACTAL_TRANSF_WIZARD_DEMO_H_
#define MANDELBULBER2_FORMULA_DEFINITION_FRACTAL_TRANSF_WIZARD_DEMO_H_

#include "all_fractal_definitions.h"

// Class already defined by FRACTAL_CLASS(cFractalTransfWizardDemo) in all_fractal_definitions.h
// Method implementations are in fractal_transf_wizard_demo.cpp

#endif
